language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - nightly

matrix:
    allow_failures:
        - php: nightly

before_script:
    - export DISPLAY=:99.0
    - Xvfb $DISPLAY -extension RANDR &> /dev/null &
    - curl http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar > selenium.jar
    - curl https://chromedriver.storage.googleapis.com/2.32/chromedriver_linux64.zip > chromedriver.zip
    - unzip chromedriver.zip
    - java -jar selenium.jar &> /dev/null &
    - php -S localhost:8000 -t tests/fixtures/ &> /dev/null &
    - cp behat.yml{-dist,}
    - composer self-update
    - composer install

script:
    - ./bin/behat -fprogress

    - ./bin/box build
    - sed -i 's/Novaway\\CommonContexts\\Extension/nw_common_contexts.phar/' behat.yml
    - ./bin/behat -fprogress
